apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dealerweb
  namespace: dealer-web
spec:
  ingressClassName: nginx
  tls:
  - secretName: dealer-web-tls    
  rules:
  - host: "b2b.ppsuperwheels.com"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: dealerweb
            port:
              number: 80

status:
  loadBalancer: {}
