apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dealerweb
  namespace: dealer-web
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/configuration-snippet: |-
      proxy_ssl_server_name on;
      proxy_ssl_name $host;
    nginx.ingress.kubernetes.io/from-to-www-redirect: 'true'
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - dealer.home.local
    secretName: dealer-web-cert
  rules:
  - host: dealer.home.local
    http:
      paths:
      - backend:
          service:
            name: dealerweb
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
