name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build-to-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.6'
          channel: 'stable'
      - run: flutter --version
      - run: flutter build web --release --base-href /b2b_dealer/
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git --work-tree build/web add --all
      - run: git commit -m "Automatic deployment by github-actions"
      - run: git push origin HEAD:gh-pages --force

  build-to-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: opas/b2bdealer-ui:1.0.0
#     - uses: actions/checkout@v3
#     - name: Set up Docker Buildx
# +        uses: docker/setup-buildx-action@v2
#     - name: docker login
#       env:
#         DOCKER_USER: ${{secrets.DOCKER_USER}}
#         DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
#       run: |
#         docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag opas/b2bdealer-ui:1.0.0
      
#     - name: Docker Push
#       run: docker push opas/b2bdealer-ui:1.0.0

    # steps:
    #   - uses: actions/checkout@v2 # Only works with v2
    #   - uses: subosito/flutter-action@v1
    #   - uses: bluefireteam/flutter-gh-pages@v7
    #     with:
    #       baseHref: /b2b_dealer/
    #       webRenderer: html